### ISSUE TITLE
Prescription Manager

### ISSUE THREAD

**Issue by suba-krishnan** [chingu-voyages/v42-bears-team-38#15]
**__Feature Description__**
Develop a responsive web application to manage prescriptions for pharmacists and patients.

**__Major User Stories/tasks__**
- [ ] As a user, I'd like to see the inventory of current medications in the pharmacy.
- [ ] As a user, I'd like to search for medication using a its name to get the inventory list
- [ ] As a user, I'd like to add new patients prescription
- [ ] As a user, I'd like to check refill timeline for patient's prescription
- [ ]
